# netlify.toml - Add this file to your GitHub repository root

[build]
  # Directory to publish - change this based on your file structure
  publish = "public_html"
  
  # Build command (not needed for static sites)
  command = ""

[build.environment]
  # Node version (if needed)
  NODE_VERSION = "18"

# Form handling settings
[[plugins]]
  package = "netlify-plugin-form-submissions"

# Redirect rules for clean URLs
[[redirects]]
  from = "/books"
  to = "/books.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

# 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
